### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Mchoga** [fauzaanu/torrent_telegram_bot#4]
I just have one Question. The main.py does not run concurrently right? meaning all the requests from users will be queued one after thre other?

**Comment by fauzaanu** [comment]
yes correct! 
The idea was there will be a small amount of users / one user per bot rather than leaving for public use as the webtor api would cost a lot of money at scale if leaving for public use.

**Comment by Mchoga** [comment]
That makes sense.  Thank you
